# Generated by Django 3.2.8 on 2021-10-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20211026_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='prize',
            field=models.CharField(blank=True, choices=[('RESUBMIT', 'RESUBMIT'), ('WAIVE_LATE_ATTENDANCE', 'WAIVE_LATE_ATTENDANCE'), ('DONATE', 'DONATE'), ('WAIVE_LATE_SUBMISSION', 'WAIVE_LATE_SUBMISSION'), ('RANDOM_3D_ITEM', 'RANDOM_3D_ITEM'), ('+1_MARK', '+1_MARK')], max_length=80),
        ),
    ]
