# Generated by Django 3.2.8 on 2021-10-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fulfilled_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.CharField(blank=True, choices=[('py-d6', 'py-d6')], default='py-d6', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('ta', 'TA'), ('student', 'Student')], default='student', max_length=80),
        ),
    ]
