# Generated by Django 3.2.8 on 2021-10-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211025_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student'), ('ta', 'TA')], default='student', max_length=80),
        ),
    ]
